name: flutter_ecom_project
description: "A new Flutter project."

publish_to: 'none' 


version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter



  #Utility packages
  http: ^1.1.0
  intl: ^0.20.2
  logger: ^2.6.0
  url_launcher: ^6.1.12
  flutter_native_splash: ^2.4.6
  smooth_page_indicator: ^1.2.1


  #Icons
  iconsax: ^0.0.8
  cupertino_icons: ^1.0.8

  #state management
  get: ^4.7.2
  get_storage: ^2.1.1



dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^5.0.0





flutter:

  uses-material-design: true

  #local Assets
  assets:
    - assets/logos/
    - assets/icons/brands/
    - assets/images/on_boarding_image/
    - assets/images/socialMedia/
    - assets/images/login/

    #local fonts
  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Black.ttf
        - asset: assets/fonts/Poppins-BlackItalic.ttf
        - asset: assets/fonts/Poppins-Bold.ttf
        - asset: assets/fonts/Poppins-BoldItalic.ttf
        - asset: assets/fonts/Poppins-ExtraBold.ttf
        - asset: assets/fonts/Poppins-ExtraBoldItalic.ttf
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Italic.ttf
        - asset: assets/fonts/Poppins-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
